const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function marked(sample){const rs=[...(sample.ranges||[])].sort((a,b)=>a.start-b.start);let out='',cur=0;for(const r of rs){out+=esc(sample.sentence.slice(cur,r.start));out+=`<span class="${r.role}">${esc(sample.sentence.slice(r.start,r.end))}</span>`;cur=r.end;}return out+esc(sample.sentence.slice(cur));}
function exactHostPattern(host){return `^${String(host||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`;}
function cleanSample(sample){if(!sample||typeof sample!=='object')return sample;const {review,...rest}=sample;return rest;}
function cleanStats(stats={}){const {reviewedCorrect,reviewedWrong,wrongByRole,...rest}=stats||{};return rest;}
async function migrateLegacyReviewData(){const {svocStats={},svocSamples=[]}=await chrome.storage.local.get(['svocStats','svocSamples']);const needsStats=['reviewedCorrect','reviewedWrong','wrongByRole'].some(k=>Object.hasOwn(svocStats,k));const needsSamples=svocSamples.some(s=>Object.hasOwn(s||{},'review'));if(needsStats||needsSamples)await chrome.storage.local.set({svocStats:cleanStats(svocStats),svocSamples:svocSamples.map(cleanSample)});}
async function load(){const{svocStats={},svocSamples=[],diagnosticsBlacklist=[],svocHostStats={}}=await chrome.storage.local.get(['svocStats','svocSamples','diagnosticsBlacklist','svocHostStats']);const avg=svocStats.processed?svocStats.totalConfidence/svocStats.processed:0;const ms=svocStats.processed?svocStats.totalMs/svocStats.processed:0;document.querySelector('#summary').innerHTML=`<div class=card><div class=value>${svocStats.processed||0}</div>processed</div><div class=card><div class=value>${svocStats.highlighted||0}</div>highlighted</div><div class=card><div class=value>${avg?Math.round(avg*100)+'%':'—'}</div>avg confidence</div><div class=card><div class=value>${ms?ms.toFixed(2)+' ms':'—'}</div>parser / sentence</div>`;
const ta=document.querySelector('#blacklist');if(document.activeElement!==ta)ta.value=SVOCPrivacy.normalizePatterns(diagnosticsBlacklist).join('\n');
renderHosts(svocHostStats,diagnosticsBlacklist);
const root=document.querySelector('#samples');const samples=SVOCPrivacy.filterSamples(svocSamples,diagnosticsBlacklist).sort((a,b)=>a.confidence-b.confidence||b.createdAt-a.createdAt).slice(0,100);if(!samples.length){root.innerHTML='<div class=empty>Browse some English pages first. Samples will appear here unless their hostname is excluded.</div>';return;}root.innerHTML=samples.map(s=>{const skipped=!(s.ranges||[]).length;return `<div class="sample" data-id="${esc(s.id)}"><div class=sentence>${marked(s)}</div><div class=meta>${esc(s.host||'')} · ${esc(s.elementTag||'')} ${skipped?'· SKIPPED ':''}· confidence ${Math.round((s.confidence||0)*100)}% · ${esc(s.ruleId||'')} · ${(s.reasons||[]).map(esc).join(', ')}</div></div>`}).join('');}
function renderHosts(hostStats,patterns){const root=document.querySelector('#hosts');const rows=Object.entries(hostStats||{}).filter(([host])=>host&&!SVOCPrivacy.matchesHost(host,patterns)).sort((a,b)=>(b[1]?.processed||0)-(a[1]?.processed||0)||a[0].localeCompare(b[0]));if(!rows.length){root.innerHTML='<div class=empty>No analyzed hostnames yet.</div>';return;}root.innerHTML=rows.map(([host,data])=>`<div class="host-row"><div><b>${esc(host)}</b><div class=host-meta>${Number(data?.processed||0).toLocaleString()} sentences · ${Number(data?.highlighted||0).toLocaleString()} highlighted</div></div><button class="action exclude-host" data-host="${esc(host)}">Exclude</button></div>`).join('');}
async function persistBlacklist(patterns,statusText){const{svocSamples=[],svocStats={},svocHostStats={}}=await chrome.storage.local.get(['svocSamples','svocStats','svocHostStats']);const filtered=SVOCPrivacy.filterSamples(svocSamples,patterns).map(cleanSample);const removed=svocSamples.length-filtered.length;const filteredHosts=Object.fromEntries(Object.entries(svocHostStats).filter(([host])=>!SVOCPrivacy.matchesHost(host,patterns)));await chrome.storage.local.set({diagnosticsBlacklist:patterns,svocSamples:filtered,svocStats:cleanStats(svocStats),svocHostStats:filteredHosts});const status=document.querySelector('#blacklist-status');status.className='status ok';status.textContent=statusText||`Saved. Purged ${removed} stored sample${removed===1?'':'s'}. Reload open pages for exclusion to take effect.`;await load();}
async function saveBlacklist(){const status=document.querySelector('#blacklist-status');const raw=document.querySelector('#blacklist').value;const patterns=SVOCPrivacy.normalizePatterns(raw);const compiled=SVOCPrivacy.compile(patterns);if(compiled.invalid.length){status.className='status err';status.textContent=`Invalid regex: ${compiled.invalid[0].source} — ${compiled.invalid[0].message}`;return;}await persistBlacklist(patterns);}
async function excludeHost(host){const{diagnosticsBlacklist=[]}=await chrome.storage.local.get('diagnosticsBlacklist');const pattern=exactHostPattern(host);const patterns=SVOCPrivacy.normalizePatterns([...diagnosticsBlacklist,pattern]);await persistBlacklist(patterns,`${host} added to exclusions. Existing diagnostics for this host were purged. Reload pages on this host.`);}
document.addEventListener('click',e=>{const btn=e.target.closest('.exclude-host');if(btn)excludeHost(btn.dataset.host).catch(()=>{});});
document.querySelector('#save-blacklist').addEventListener('click',()=>saveBlacklist().catch(()=>{}));
document.querySelector('#export').addEventListener('click',async()=>{const{svocStats={},svocSamples=[],diagnosticsBlacklist=[]}=await chrome.storage.local.get(['svocStats','svocSamples','diagnosticsBlacklist']);const safeSamples=SVOCPrivacy.filterSamples(svocSamples,diagnosticsBlacklist).map(cleanSample);const safeStats=cleanStats(svocStats);const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),svocSamples:safeSamples,svocStats:safeStats},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`svoc-diagnostics-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
document.querySelector('#reset').addEventListener('click',async()=>{if(!confirm('Reset metrics, samples, and analyzed-host counts? Excluded hostname settings will be kept.'))return;await chrome.storage.local.remove(['svocStats','svocSamples','svocHostStats']);load();});
(async()=>{await migrateLegacyReviewData();await load();})();
